### ISSUE TITLE
User Interface doesn't start with gnome 3.22  and Wayland

### ISSUE THREAD

**Issue by Paullux** [Ashark/archlinux-amdgpu-pro#19]
When i update my pc on ArchLinux, there is 3 days ago (the october 11th 2016) : X, Gnome and GDM refuse to start.

I should uninstall all componantes of AMDGPU-PRO driver to restart GDM and Gnome.

**Comment by maxcr** [comment]
You need to use the latest LLVM-dev and Mesa-dev for everything to work right.

**Comment by Paullux** [comment]
I tried to do `yaourt -S mesa-git llvm-svn` but that doesn't work

**Comment by maxcr** [comment]
That was the correct command. Everything build and installs correctly and its still broken? Wayland is a huge buggy piece of shit. I used it for two days. It uses 2 GB of ram and crashes all the time. Would not recommend. If you do manage to get some sort of Xsession running try to see if you can switch it back to xorg.

**Comment by Paullux** [comment]
The bug is caused by cogl. A patch was created but now, it doesn't work

**Comment by uKev** [comment]
I can confirm this bug. 
Installation of mesa-git and llvm-svn before compiling amdgpu-pro didn't help for me. Only a black screen with a moving cursor appears. 

In dmesg there are segfaults in amdgpu_dri.so.

startx at least starts an xserver, but most stuff there crashes and doesn't really work.

cogl-amdgpu-pro doesn't help either. Comments in the aur package seem that it's a general issue:
https://aur.archlinux.org/packages/cogl-amdgpu-pro/

**Comment by corngood** [comment]
16.60 is out now.  Can anyone test this?

**Comment by JontySR** [comment]
Just tried logging into wayland, and got kicked back to the log in screen.

**Comment by Ashark** [comment]
Stale
