### ISSUE TITLE
Missing ubuntu version ./extract_transaction_scripts_and_triggers.sh

### ISSUE THREAD

**Issue by NonaSuomy** [Ashark/archlinux-amdgpu-pro#63]
majornew=$pkgver_base
minornew=$pkgver_build
ubuntuvernew=$ubuntu_ver

majorold=20.20
minorold=1098277
ubuntuverold=20.04

# Switch for running this script against another release. Use NEW or OLD values
RUN_FOR_VERSION=NEW
# RUN_FOR_VERSION=OLD

if [ $RUN_FOR_VERSION == "NEW" ]; then
    major=$majornew
    minor=$minornew
    ubunt=$ubuntuvernew
elif [ $RUN_FOR_VERSION == "OLD" ];then
    major=$majorold
    minor=$minorold
    ubunt=$ubuntuverold
fi

ARCHIVE=amdgpu-pro-$major-$minor-ubuntu-$ubunt.tar.xz

**Comment by Ashark** [comment]
Now packages are published in repo, not in archive. Also currently using a single versions file, which is interpreted both by bash and python.
