### ISSUE TITLE
KDE doesn't start

### ISSUE THREAD

**Issue by Thecrafterja** [Ashark/archlinux-amdgpu-pro#68]
Hello!

I have a problem: KDE and X.Org doesn't start after rebooting. DaVinci Resolve is running with amdgpu-pro-lib and opencl-amdgpu-pro-pal. 

OS: Manjaro
Graphics card: Powercolor AMD Vega 56
CPU: Ryzen 9 3900X
 I hope, somebody can help me.

Sorry for bad english...

Thecrafterja

**Comment by Ashark** [comment]
As of 20.45_1188099-5, I have disabled it from auto loading, and you can invoke desired application with `progl` prefix.
