### ISSUE TITLE
==> ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by neondeex** [Ashark/archlinux-amdgpu-pro#69]
⌠ ⚡⌡▷ pamac build amdgpu-pro-libgl                                          
Preparing...
Cloning amdgpu-pro-installer build files...
Checking amdgpu-pro-libgl dependencies...
Resolving dependencies...
Checking inter-conflicts...

To build (1):
amdgpu-pro-libgl  20.45_1188099-5    AUR

Edit build files : [e] 
Apply transaction ? [e/y/N] y

Building amdgpu-pro-installer...
==> Making package: amdgpu-pro-installer 20.45_1188099-5 (Tue 09 Feb 2021 11:55:23 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Found amdgpu-pro-20.45-1188099-ubuntu-20.04.tar.xz
-> Found progl
-> Found progl.bash-completion
==> Validating source files with sha256sums...
amdgpu-pro-20.45-1188099-ubuntu-20.04.tar.xz ... FAILED
progl ... Passed
progl.bash-completion ... Passed
==> ERROR: One or more files did not pass the validity check!
Error: Failed to build amdgpu-pro-installer

**Comment by neondeex** [comment]
Why do i get this error?

**Comment by Ashark** [comment]
Please try the current version.
