### ISSUE TITLE
Build opencl packages from this PKGBUILD?

### ISSUE THREAD

**Issue by maz-1** [Ashark/archlinux-amdgpu-pro#70]
Currently closed source opencl driver is installed via https://aur.archlinux.org/packages/opencl-amd
AFAIK it shares the same zip file with amdgpu-pro-installer so it would be better to merge opencl-amd into this PKGBUILD

**Comment by Ashark** [comment]
Sorry for late reply.
The publish scheme changed, and now they use repo and not an archive.
