### ISSUE TITLE
Updating to install version 21.40?

### ISSUE THREAD

**Issue by DeadlandStrider** [Ashark/archlinux-amdgpu-pro#71]
Are you going to update this for the new AMD 21.40 driver? 
I believe I need the updated driver to use AMD HIP acceleration in Blender 3.0 on Linux. 

Anyway, you are great! 

Thanks for all you do!

**Comment by dPing** [comment]
I second this question.  I have 3 "marked out of date" packages from the AUR
amf-amdgpu-pro  lib32-vulkan-amdgpu-pro  vulkan-amdgpu-pro

**Comment by Ashark** [comment]
Updated to 22.10.3
