### ISSUE TITLE
Custom variables should use underscores

### ISSUE THREAD

**Issue by sfan5** [Ashark/archlinux-amdgpu-pro#77]
https://github.com/Ashark/archlinux-amdgpu-pro/blob/bba7ca3722ea7495ff44532a372863c763849e29/gen-PKGBUILD.py#L260-L264

As stated in PKGBUILD(5):
> If you need to create any custom variables for use in your build process, it is recommended to prefix their name with an _ (underscore).

Same for the functions I guess.

**Comment by Ashark** [comment]
Thanks for you suggestion. To be honest, I don't very like this idea. Lines are already long enough:
` extract_deb "${srcdir}"/vulkan-amdgpu-pro_${major_short}-${minor}~${ubuntu_ver}_i386.deb`
With this change they will be like:
` extract_deb "${srcdir}"/vulkan-amdgpu-pro_${_major_short}-${_minor}~${_ubuntu_ver}_i386.deb`
It just makes variables less readable. Taking into account that it is just a recommendation, I prefer to keep a more readable variant. And will pay attention on possible conflicts.
But again, thanks for your suggestion.
