### ISSUE TITLE
My graph RX6800XT does not work with driver 20.40

### ISSUE THREAD

**Issue by CodigoCristo** [Ashark/archlinux-amdgpu-pro#83]
https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-45

pls

**Comment by CodigoCristo** [comment]
this can help me

![image](https://user-images.githubusercontent.com/34531165/212551374-b4fbda7a-9fac-4ad1-9fcc-ae6e24483af1.png)

**Comment by emaxoda** [comment]
That looks like a really old build for the AMDGPU Pro drivers. Why do you think you need that?
Those cards should work with the lastest version provided by this package.

**Comment by mesmerx** [comment]
the opensource is the mesa radv driver if i am not wrong

**Comment by mesmerx** [comment]
this package is to build the pro driver (for amf and such), did you installed that? because your prints only show the mesa driver

**Comment by CodigoCristo** [comment]
![image](https://user-images.githubusercontent.com/34531165/221549111-22cac737-6c2a-4adf-bf1e-dd327b414afb.png)
Help pls

**Comment by CodigoCristo** [comment]
o It will be to install mesa-git

**Comment by CodigoCristo** [comment]
![image](https://user-images.githubusercontent.com/34531165/221549711-cecc20c6-a79f-41da-a96b-c1fcd723b48e.png)

**Comment by mesmerx** [comment]
again the driver is at 22.40 not 20.40, do you have this package installed did you installed https://aur.archlinux.org/packages/amdgpu-pro-oglp????

**Comment by mesmerx** [comment]
i`ll close this issue as this dont make much sense with the information given, please reopen if you find its needed
