### ISSUE TITLE
Failed to connect to repo.radeon.com

### ISSUE THREAD

**Issue by tetoNidan** [Ashark/archlinux-amdgpu-pro#90]
[general Question]

installing through [git](https://aur.archlinux.org/packages/amdgpu-pro-oglp)
curl: (28) Failed to connect to repo.radeon.com port 443 after 129320 ms: Couldn't connect to server

Been trying for a few hours and was wondering if there is a change in deb file location?

Also tried following the directions on the [code](https://github.com/Ashark/archlinux-amdgpu-pro) page, dpkg-deb and aptly is not in pacman. Doing a search for either provides no results in pacman. Aptly is in the AUR though but dpkg-deb is not. Will that cause issues when installing through PKGBUILD?

Thanks!

**Comment by mesmerx** [comment]
about dpkg you can use dpkg-git, its only to create the MAKEPKG file,  if you use the Makepkg file already created (and git added)  this will not matter

about the file downloads it seems a route problem, here the downloads is fine it seems
![20230618_20h09m40s_grim](https://github.com/Ashark/archlinux-amdgpu-pro/assets/16441524/ea96e95e-c98a-4644-a06b-75f55209476b)

**Comment by mesmerx** [comment]
it happens a lot of times with resolv problems, try to use resolved
https://wiki.archlinux.org/title/Systemd-resolved

**Comment by tetoNidan** [comment]
Thanks, I have been able to `makepkg` from git. However which file do I use for `sudo pacman -U package_name`? Guess I'm a little unclear. I see several files that have `.pkg.tar.zst`, I would assume I would install each individually? Sorry kind of a noob to arch and this is my first AUR-git build. 

So please tell me if im wrong but since I have a 64 bit OS I would do the following:

    sudo pacman -U amdgpu-pro-oglp-23.10_1595145-1-x86_64.pkg.tar.zst 
    sudo pacman -U amdgpu-pro-oglp-23.10_1595145-1-x86_64.pkg.tar.zst 
    sudo pacman -U lib32-amdgpu-pro-oglp-23.10_1595145-1-x86_64.pkg.tar.zst
    sudo pacman -U lib32-vulkan-amdgpu-pro-23.10_1595145-1-x86_64.pkg.tar.zst
    sudo pacman -U vulkan-amdgpu-pro-23.10_1595145-1-x86_64.pkg.tar.zst

Or is there a single file to build them all at once? I think the former is the answer but I don't want to mess anything up. The reason I ask is when reading the PKGBUILD file I see calls to move files to locations. My bash programming is subpar though so I thought it best to ask.

Thanks.

**Comment by tetoNidan** [comment]
I figured it out. For the noobs out there reading this `makepkg -i` is the magic.

Thanks [mesmerx](https://github.com/mesmerx)!
